[package]
name = "r6502"
version = "0.1.0"
authors = ["Marcus Borkenhagen <m@fritschy.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.16"
stopwatch = "0.0.7"